1. Documentation reading

In [ ]:
# No code solution (reading)

2. Create a random tensor with shape (7, 7).

In [5]:
import torch

# Create a random tensor
random_tensor = torch.rand(7, 7)
print(random_tensor)

tensor([[0.2146, 0.5757, 0.6543, 0.9488, 0.6553, 0.4470, 0.8430],
        [0.0086, 0.6964, 0.7966, 0.0517, 0.3878, 0.9323, 0.9355],
        [0.6340, 0.2182, 0.1635, 0.5601, 0.4240, 0.4061, 0.5875],
        [0.1352, 0.1077, 0.2375, 0.5397, 0.9754, 0.2193, 0.8250],
        [0.9126, 0.0789, 0.8400, 0.8491, 0.2048, 0.6793, 0.4705],
        [0.5868, 0.5600, 0.4111, 0.4166, 0.4413, 0.2081, 0.5686],
        [0.4879, 0.8476, 0.3635, 0.4952, 0.5336, 0.7924, 0.6558]])


3. Perform a matrix multiplication on the tensor from step 1 with another random tensor with shape (1, 7). (Hint: You may need to transpose the second tensor.)

In [6]:
# Create another random tensor with shape (1, 7)
tensor_b = torch.rand(1, 7)

# Transpose the second tensor to (7, 1) for matrix multiplication
tensor_b_transposed = tensor_b.T

# Perform matrix multiplication
result = torch.mm(random_tensor, tensor_b_transposed)
print(result)


tensor([[1.5633],
        [1.7777],
        [1.1251],
        [1.2085],
        [1.5697],
        [1.1419],
        [1.5949]])


4. Set the random seed to 0 and do 2 & 3 over again.

In [13]:
# Set the random seed
torch.manual_seed(0)

# Redo exercise 2
random_tensor_seeded = torch.rand(7, 7)

# Redo exercise 3
tensor_b_seeded = torch.rand(1, 7).T
result_seeded = torch.mm(random_tensor_seeded, tensor_b_seeded)
result_seeded, result_seeded.shape


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

5. Is there a GPU equivalent for setting the random seed? If yes, set the GPU random seed to 1234.

In [4]:
# Install and Import torch
!pip install torch
import torch

# Set the GPU random seed
if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)

6. Create two random tensors of shape (2, 3) and send them to the GPU. Use torch.manual_seed(1234) when creating the tensors.

In [5]:
# Set the random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
# Create two random tensors on GPU
    tensor_A = torch.rand(2, 3).cuda()
    tensor_B = torch.rand(2, 3).cuda()
    print(tensor_A, tensor_B)
else:
    print("GPU not available.")

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [8]:
if torch.cuda.is_available():
    # Transpose tensor_B for matrix multiplication
    tensor2_transposed = tensor_B.T
    result_gpu = torch.mm(tensor_A, tensor2_transposed)
    print(result_gpu,result_gpu.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


8. Find the maximum and minimum values of the output of 7.

In [7]:
if torch.cuda.is_available():
    # Find max
    max_value = torch.max(result_gpu)
    # Find min
    min_value = torch.min(result_gpu)
    print(f"Max: {max_value}, Min: {min_value}")

Max: 0.5617256760597229, Min: 0.3647301495075226


9. Find the maximum and minimum index values of the output of 7.

In [9]:
if torch.cuda.is_available():
    # Find arg max
    max_index = torch.argmax(result_gpu)
    # Find arg min
    min_index = torch.argmin(result_gpu)
    print(f"Max Index: {max_index}, Min Index: {min_index}")

Max Index: 3, Min Index: 0


10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [24]:
# Set seed
torch.manual_seed(7)

# Create a random tensor
dim4_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_squeezed = dim4_tensor.squeeze()

# Print out tensors and their shapes
print(dim4_tensor,dim4_tensor.shape)
print(tensor_squeezed,tensor_squeezed.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
